In [ ]:
# broadcasting

In [7]:
import numpy as np

In [12]:
arr1 = np.arange(30).reshape(5,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
arr2 = np.arange(30).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,6) (6,5) 

In [16]:
x = np.array([10,20,30])
x

array([10, 20, 30])

In [17]:
x.ndim

1

In [19]:
y = np.array([[1],[2],[3],[4]])
y

array([[1],
       [2],
       [3],
       [4]])

In [20]:
y.ndim

2

In [21]:
x+y

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [22]:
type(x+y)

numpy.ndarray

In [23]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
arr3 = np.array([500,600,700,800,900])
arr3

array([500, 600, 700, 800, 900])

In [31]:
arr2 + arr3

array([[500, 601, 702, 803, 904],
       [505, 606, 707, 808, 909],
       [510, 611, 712, 813, 914],
       [515, 616, 717, 818, 919],
       [520, 621, 722, 823, 924],
       [525, 626, 727, 828, 929]])

In [34]:
a = np.arange(20)
b = np.arange(8)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7]


In [35]:
a + b

ValueError: operands could not be broadcast together with shapes (20,) (8,) 

In [37]:
arr5 = np.arange(20).reshape(4,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
arr6 = np.arange(3)
arr6

array([0, 1, 2])

In [43]:
arr5 + arr6

ValueError: operands could not be broadcast together with shapes (4,5) (3,) 

In [ ]:
# splitting 1D array

In [49]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
np.split(x,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [51]:
y = np.arange(30)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
np.split(y,15)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19]),
 array([20, 21]),
 array([22, 23]),
 array([24, 25]),
 array([26, 27]),
 array([28, 29])]

In [56]:
np.split(y,3)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]

In [57]:
np.split(y,11)

ValueError: array split does not result in an equal division

In [61]:
np.split(y,15)[0] #[0] is the index #accessing the subparts

array([0, 1])

In [66]:
np.split(y,15,axis=0)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19]),
 array([20, 21]),
 array([22, 23]),
 array([24, 25]),
 array([26, 27]),
 array([28, 29])]

In [67]:
np.split(y,15) #default axis is zero

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19]),
 array([20, 21]),
 array([22, 23]),
 array([24, 25]),
 array([26, 27]),
 array([28, 29])]

In [ ]:
# splitting 2D array

In [68]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
np.split(x,5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [72]:
np.split(x,5,axis=0)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [73]:
np.split(x,5,axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [76]:
y = np.arange(50).reshape(5,10)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
np.split(y,5,axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])]

In [83]:
np.split(y,10,axis=1)

[array([[ 0],
        [10],
        [20],
        [30],
        [40]]),
 array([[ 1],
        [11],
        [21],
        [31],
        [41]]),
 array([[ 2],
        [12],
        [22],
        [32],
        [42]]),
 array([[ 3],
        [13],
        [23],
        [33],
        [43]]),
 array([[ 4],
        [14],
        [24],
        [34],
        [44]]),
 array([[ 5],
        [15],
        [25],
        [35],
        [45]]),
 array([[ 6],
        [16],
        [26],
        [36],
        [46]]),
 array([[ 7],
        [17],
        [27],
        [37],
        [47]]),
 array([[ 8],
        [18],
        [28],
        [38],
        [48]]),
 array([[ 9],
        [19],
        [29],
        [39],
        [49]])]