In [3]:
import numpy as np

In [4]:
arr1 = np.array([10,20,30])
arr1

array([10, 20, 30])

In [5]:
arr2 = np.arange(1,50,17)
arr2

array([ 1, 18, 35])

In [6]:
arr3 = np.arange(1,51,18)
arr3

array([ 1, 19, 37])

In [8]:
arr2 = np.linspace(1,50,16)
arr2

array([ 1.        ,  4.26666667,  7.53333333, 10.8       , 14.06666667,
       17.33333333, 20.6       , 23.86666667, 27.13333333, 30.4       ,
       33.66666667, 36.93333333, 40.2       , 43.46666667, 46.73333333,
       50.        ])

In [15]:
arr4 = np.linspace(1,12,12)
print(arr4)
print(type(arr4))
print(arr4.ndim)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
<class 'numpy.ndarray'>
1


In [17]:
arr5 = arr4.reshape(6,2)
print(arr5)
print(arr5.ndim)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
2


In [26]:
arr6 = np.arange(12).reshape(6,2)
arr6

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
# row and column vector

In [28]:
arr7 = np.arange(5).reshape(1,5)
arr7

array([[0, 1, 2, 3, 4]])

In [30]:
# arr8 = np.arange(10).reshape(1,10)    #row
arr8

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
arr8 = np.arange(10).reshape(10,1)      #column
arr8

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# Dealing with wrong parameters

In [36]:
arr9 = np.arange(20).reshape(10,2)
arr9

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [43]:
arr9 = np.arange(20).reshape(10,-19)
arr9

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [44]:
arr9 = np.arange(18).reshape(6,9) #wrong parameter will be recalculated by numpy , autocorrect
arr9

ValueError: cannot reshape array of size 18 into shape (6,9)

In [45]:
arr9 = np.arange(10).reshape(5,)
arr9

ValueError: cannot reshape array of size 10 into shape (5,)

In [ ]:
# Initial Placeholders

In [ ]:
# ZEROES

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros([5,5]) #use [] for dimension values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Ones

In [53]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# identity matrix

In [55]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# diag

In [57]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [58]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])