In [4]:
import numpy as np

In [6]:
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr1[5]

15

In [ ]:
# slicing

In [8]:
arr1[1:3]

array([11, 12])

In [6]:
arr1[5:8]

array([15, 16, 17])

In [7]:
arr1[0:5:2]

array([10, 12, 14])

In [8]:
arr1[0:6:3]

array([10, 13])

In [17]:
arr1[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [16]:
arr1[-2:-5:-1]

array([19, 18, 17])

In [ ]:
# with 2D arrays

In [9]:
arr2 = np.arange(20).reshape(5,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
arr2.ndim

2

In [10]:
arr2[0]

array([0, 1, 2, 3])

In [11]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
arr2[1]

array([4, 5, 6, 7])

In [13]:
arr2[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr4 = np.arange(50).reshape(5,10)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
arr4[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr4[0:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr4[0:4:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [23]:
arr4[0][0]

0

In [24]:
arr4[2][2]

12

In [25]:
arr4[5][0]

25

In [28]:
arr4[4:6][1:3]

array([[25, 26, 27, 28, 29]])