In [1]:
a1 = [1,2,3,4,5,6,7,8,9]
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
for x in a1:
    print(x*2)

2
4
6
8
10
12
14
16
18


In [4]:
a2 = [x*2 for x in a1]
print(a2)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [6]:
print(a1)
for x in a1:
    print(x*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
2
4
6
8
10
12
14
16
18


In [8]:
a3 = [x**2 for x in a1]
print(a3)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [9]:
print('hello world')

hello world


In [11]:
name = "monty"
print(name.casefold())

monty


In [13]:
import numpy as np
arr1 = np.array(a1)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [14]:
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
a1*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
print(arr1*2)

[ 2  4  6  8 10 12 14 16 18]


In [19]:
print(arr1*3)

[ 3  6  9 12 15 18 21 24 27]
