In [3]:
a1 = [10,20,30,40]
print(a1)
print(type(a1))

[10, 20, 30, 40]
<class 'list'>


In [4]:
import numpy as np

In [5]:
arr1 = np.array(a1)
print(arr1)

[10 20 30 40]


In [6]:
type(arr1)

numpy.ndarray

In [11]:
num = 100
x = str(num)
print(x)
print(type(x))
print(type(arr1))

100
<class 'str'>
<class 'numpy.ndarray'>


In [16]:

elementwise operation

In [18]:
for x in a1:
    print(x*2)

20
40
60
80


In [21]:
a2 = [x*2 for x in a1]
print(a2)
print(type(a2))

[20, 40, 60, 80]
<class 'list'>


In [25]:
arr1*2

array([20, 40, 60, 80])

In [26]:
type(arr1*2)

numpy.ndarray

In [27]:
arr1**2

array([ 100,  400,  900, 1600])

In [28]:
arr1*arr1

array([ 100,  400,  900, 1600])

In [29]:
arr1+arr1

array([20, 40, 60, 80])

In [30]:
arr1*arr1*arr1

array([ 1000,  8000, 27000, 64000])

In [31]:
arr1

array([10, 20, 30, 40])

In [38]:
arr2 = np.array([1,2,3])
print(arr2)

[1 2 3]


In [39]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 