In [ ]:
import numpy as np

In [ ]:
# indexing with boolean arrays

In [28]:
arr1 = np.arange(12).reshape(4,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
arr1 + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [5]:
arr1 > 10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [6]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
arr1 > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr1 < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [9]:
arr1 % 2 == 0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [10]:
arr1 % 2 != 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [11]:
arr1 % 3 == 0

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [12]:
# multiple conditions

In [21]:
(arr1 % 2 == 0) & (arr1 % 3 == 0)

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [23]:
arr2 = (arr1 % 2 == 0) | (arr1 % 3 == 0)
arr2

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [27]:
arr1

array([[ True, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [25]:
arr2

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [26]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([False, False, False, False, False, False, False, False, False,
       False])

In [29]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
arr2

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [31]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [33]:
arr1[arr1>10]

array([11])

In [34]:
arr1[(arr1 %2 == 0) & (arr1 %3 == 0)]

array([0, 6])

In [ ]:
# https://numpy.org/doc/stable/user/quickstart.html#universal-functions

In [37]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[10 20 30 40 50]
[1 2 3 4 5]


In [40]:
a + 10

array([20, 30, 40, 50, 60])

In [41]:
b + 5

array([ 6,  7,  8,  9, 10])

In [42]:
a

array([10, 20, 30, 40, 50])

In [43]:
a + b

array([11, 22, 33, 44, 55])

In [44]:
a % b

array([0, 0, 0, 0, 0])

In [45]:
a * b

array([ 10,  40,  90, 160, 250])

In [46]:
a - b 

array([ 9, 18, 27, 36, 45])

In [47]:
a / b

array([10., 10., 10., 10., 10.])

In [48]:
b / a

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [49]:

a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 0]


In [50]:
a/b

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15036\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([11., 11., 11., 11., inf])

In [51]:
a % b

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15036\2189094906.py:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([0, 0, 0, 0, 0])

In [52]:
b / a

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.        ])

In [53]:
a = np.array([11,22,33,44])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44]
[1 2 3 4 5]


In [54]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [57]:
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])

In [76]:
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [68]:
n = s[2,1:]
print(n)

['Riya' 'Devanshi']


In [72]:
g = s[1,0:]
g

array(['Neha', 'Avni', 'Akash'], dtype='<U8')

In [74]:
h = s[1:, :]
print(h)

[['Neha' 'Avni' 'Akash']
 ['Arjun' 'Riya' 'Devanshi']]


In [75]:
y = s[0:, :]
print(y)

[['Priya' 'Rohit' 'Aryan']
 ['Neha' 'Avni' 'Akash']
 ['Arjun' 'Riya' 'Devanshi']]


In [77]:
s[1,1]

'Avni'

In [78]:
score = np.random.randint(10,100,15).reshape(5,3)
print(score)

[[20 24 32]
 [38 14 39]
 [41 63 58]
 [63 76 57]
 [58 75 92]]


In [79]:
score[score>50]

array([63, 58, 63, 76, 57, 58, 75, 92])

In [81]:
score[score<35]

array([20, 24, 32, 14])