In [2]:
import numpy as np

In [3]:
# 1D ARRAY
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[10 20 30 40 50]
[1 2 3 4 5]


In [6]:
a + b

array([11, 22, 33, 44, 55])

In [7]:
a - b

array([ 9, 18, 27, 36, 45])

In [8]:
a * b

array([ 10,  40,  90, 160, 250])

In [9]:
a % b

array([0, 0, 0, 0, 0])

In [10]:
a / b

array([10., 10., 10., 10., 10.])

In [11]:
np.sum(a)

150

In [12]:
np.sum(b)

15

In [13]:
np.min(a)

10

In [14]:
np.min(b)

1

In [15]:
np.max(a)

50

In [16]:
np.max(b)

5

In [17]:
np.mean(a)

30.0

In [18]:
np.mean(b)

3.0

In [19]:
# 2D ARRAY

In [21]:
len(np.arange(20,70,2))

25

In [39]:
arr1 = np.arange(30,70,2).reshape(5,4)
arr1

array([[30, 32, 34, 36],
       [38, 40, 42, 44],
       [46, 48, 50, 52],
       [54, 56, 58, 60],
       [62, 64, 66, 68]])

In [40]:
np.sum(arr1)

980

In [42]:
np.sum(arr1,axis=0) #sum of columns

array([230, 240, 250, 260])

In [43]:
np.sum(arr1,axis=1) #sum of rows

array([132, 164, 196, 228, 260])

In [48]:
np.max(arr1)

68

In [49]:
np.max(arr1,axis=1)

array([36, 44, 52, 60, 68])

In [50]:
np.max(arr1,axis=0)

array([62, 64, 66, 68])

In [51]:
np.mean(arr1,axis=0)

array([46., 48., 50., 52.])

In [52]:
np.mean(arr1,axis=1)

array([33., 41., 49., 57., 65.])

In [55]:
score = np.random.randint(20,200,25).reshape(5,5)
score

array([[154,  21,  42, 185,  72],
       [199, 189,  44,  45, 132],
       [ 99, 147, 184, 106,  76],
       [122, 188, 196, 134,  45],
       [ 80, 121, 173,  95,  22]])

In [56]:
np.sum(score,axis=0) #column-0

array([654, 666, 639, 565, 347])

In [57]:
np.sum(score,axis=1) #rows-1

array([474, 609, 612, 685, 491])

In [58]:
np.mean(score,axis=1)

array([ 94.8, 121.8, 122.4, 137. ,  98.2])

In [59]:
np.mean(score,axis=0)

array([130.8, 133.2, 127.8, 113. ,  69.4])