In [3]:
import numpy as np

In [4]:
data = np.loadtxt('fitbit.txt', dtype='str')

In [8]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [9]:
print(type(data))

<class 'numpy.ndarray'>


In [10]:
data.ndim

2

In [11]:
data.shape

(26, 7)

In [12]:
data.size

182

In [13]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [14]:
data[10]

array(['16-10-2017', '9690', '300', '331', '5', '0', '68'], dtype='<U10')

In [15]:
data[0:10]

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68']], dtype='<U10')

In [16]:
data[0:10:2]

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68']], dtype='<U10')

In [17]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [6]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [19]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [22]:
data.T[6]

array(['68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68'], dtype='<U10')

In [25]:
tuple_1 = (10,20,30,40) #packing of tuple
print(tuple_1[0])
print(tuple_1[1])
print(tuple_1[2])

10
20
30


In [27]:
a,b,c,d=tuple_1 #unpacking a tuple
print(a)
print(b)

10
20


In [8]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg=data.T

In [9]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [10]:
calories_burned

array(['181', '208', '341', '190', '307', '302', '198', '201', '195',
       '327', '331', '318', '344', '204', '180', '201', '329', '315',
       '197', '184', '328', '322', '327', '148', '235', '184'],
      dtype='<U10')

In [ ]:
# Data types in NUMPY

In [ ]:
# https://numpy.org/doc/stable/user/basics.types.html

In [11]:
step_count.dtype

dtype('<U10')

In [12]:
type(step_count)

numpy.ndarray

In [ ]:
# changing the string data type to 'int'

In [13]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [14]:
mood= np.array(mood,dtype='int')

In [15]:
mood

array([200, 200, 300, 100, 300, 300, 100, 200, 200, 300, 300, 300, 300,
       200, 200, 200, 300, 300, 100, 100, 300, 300, 300, 100, 200, 200])

In [16]:
mood.dtype

dtype('int32')

In [17]:
# changing the data types of other parameters to 'int'

In [18]:
calories_burned=np.array(calories_burned,dtype='int')
hours_of_sleep=np.array(hours_of_sleep,dtype='int')
step_count=np.array(step_count,dtype='int')

In [19]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [22]:
step_count.dtype

dtype('int32')

In [23]:
hours_of_sleep.dtype

dtype('int32')

In [24]:
mood

array([200, 200, 300, 100, 300, 300, 100, 200, 200, 300, 300, 300, 300,
       200, 200, 200, 300, 300, 100, 100, 300, 300, 300, 100, 200, 200])

In [25]:
np.unique(mood)

array([100, 200, 300])

In [26]:
mood == '100'
mood[mood == '100'] = 'sad'

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17892\858163199.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mood == '100'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17892\858163199.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mood[mood == '100'] = 'sad'


ValueError: invalid literal for int() with base 10: 'sad'

In [27]:
mood= np.array(mood,dtype='U10')

In [28]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [29]:
mood == '100'
mood[mood == '100'] = 'sad'

In [30]:
mood == '200'
mood[mood == '200'] = 'neutral'

In [31]:
mood == '300'
mood[mood == '300'] = 'happy'

In [32]:
mood

array(['neutral', 'neutral', 'happy', 'sad', 'happy', 'happy', 'sad',
       'neutral', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'neutral', 'neutral', 'neutral', 'happy', 'happy', 'sad', 'sad',
       'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral'],
      dtype='<U10')